dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install pandas${PANDAS_VERSION} plotly${PLOTLY_VERSION}
- pip install .[test]
script:
- pytest
env:
- PANDAS_VERSION=">=1.12"
- PANDAS_VERSION=">=1.1,<1.2"
- PANDAS_VERSION=">=1.0,<1.1"
- PLOTLY_VERSION=">=4.0.0"
- PLOTLY_VERSION=">=3.9.0,<4.0.0"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: An2YDpqWJoWSV50ox1aKCbFU/7hok1cQrOWQHndvRGpbXRFyCY4SVFa3LqFYqOHs37P3iBfG/wUqC6Cw+GgykOlyFBmlz6MyB3PQZt7UXKpcvz4yE3u8OEcls5Q6Z9k0VxelvBpuTn34Ilo+xSZOTqrR3BAzGBSbD8AhLCVcCQn79i06sJAXudBw0F5Ab1K94Lkc1XxsBKWrIbXGWVHvMN35e4t9m+VPODNNigE1K3q8NhHnjyZI9v/Fd7+e2VJWdwT4bQ1CPv5cC3YPNCFhTCqVvCtPCLXxzBq090XXrHT6/yZjVgjk3LzQxKA+kGhnXKBl2mBHGlmxumJlecxPBl1bVXOhfqPYx7CNTUpTi3XT+xb1bcT6MuS1XhANCdhKVO9BeFo4lzLsTaJOP55uEQp2ss//jKGtYOvEUdiv8ky3zjzadiNJHy88rsv8wCOjNVHgCDgx9nu0Ufo/99UAEs5cCSX9moWsGmEPeNaRvz5HT+VelBj9lj/ooa/BSopiZCSUsk1YqGRhfBo8PZzvvDBYhR5oMjokO8uRaLXwQmJss8w5ihBTuoeECNVZSKdcaKq3jeWNVlYb7s3T9T0fyX4jqdi1tATIWIVP5LyjxQIvTbyfYyyvimEWA4dnTtJaAew7Qtlqc4geRKMwiDKFTLaRZ0H8nerIUkQ6f3+RBLM=
  on:
    tags: true
  skip_existing: true
