dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install pandas${PANDAS_VERSION} plotly${PLOTLY_VERSION}
- pip install .[test]
script:
- pytest
env:
- PANDAS_VERSION=">=0.24.0"
- PANDAS_VERSION=">=0.23.0,<0.24.0"
- PLOTLY_VERSION=">=3.9.0"
- PLOTLY_VERSION=">=3.8.0,<3.9.0"
deploy:
  provider: pypi
  user: darcyabjones
  password:
    secure: Ed4pKE7H+Lu0fqaBngEAiUcaORZulT8N2r1yRMendSGn/16CU0PKoVxMeMt9rj4nY/GAnIdviqs1LO+fNnEwWQc1zmLHvAao12jjlcakS2/qgT3KmH3TWA4LDeUmEmNHylGjPidkET2fhXMFIVuB+mFy3Ze4/KrZtFHlljCV7bBod6twbYc3+JLHGuiKQgcVKEaXqrX01uvl6eqfk5Ho3wDWiqAgpFS1Mph8koOK5721S7TAnirYC8aKpVTspp8MTCPlAlUQxaMY16CGbKbcdMAaHrqfGIJjnOYwG9yJA303jB8M9fDfnSchwhQ5eR9P07QApB3kakq08s37SwoYXW6vmYJZZNP2jb38TEZQOKSzbltEhPJX/hjBtwCqNFoDN232pT9bGgB8JAZRpujhXqTU4T9qkGPtdKEsrhjWp7Sv1FR6iG7anxyfdFa9U12u1Ht1tKMgSa/XCInlbXf08xEgMxhUBDd2EqT2eBM9+JoCbNW/JR7+ThuiXd0lNOxKziHyfheAN7qCszbndN0tNG0QVqZC0XTIx8Kue3ar3WAxflQCopDTHcMsGiTvv41W52wAXodEEReMhXouP3jpOI1D93AmX6kVUCikZAwNymkHhQDSJoyBitQsogoMuE9c6FKRXix9/hwI9RskFNxJwAMJ+tSwXKmIsBuNfeK+zrg=
  on:
    tags: true
  skip_existing: true
